# Generated by Skyramp v1.3.34 on 2026-07-21 16:09:45.145462218 +0000 UTC m=+206.165985461
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output flows_created_asc_sort_integration_test.py \
# 		--output-dir /home/runner/work/prefect-sutboot/prefect-sutboot/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-sutboot/prefect-sutboot/tests/scenario_flows_created_asc_sort.json

# Import of required libraries
import skyramp
import os
import re
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    unique_suffix = str(int(time.time() * 1000))
    flow_a_name = f"testbot-flow-asc-a-{unique_suffix}"
    flow_b_name = f"testbot-flow-asc-b-{unique_suffix}"
    # Request Body
    endpoint_1_POST_request_body = f'''{{
        "name": "{flow_a_name}"
    }}'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_1_POST_request_body
    )

    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == flow_a_name
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(endpoint_1_POST_response, "id"), re.IGNORECASE)
    assert re.match(r"^\d{4}-\d{2}-\d{2}T", skyramp.get_response_value(endpoint_1_POST_response, "created"))

    # Request Body
    endpoint_1_POST_1_request_body = f'''{{
        "name": "{flow_b_name}"
    }}'''

    # Execute Request
    endpoint_1_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_1_POST_1_request_body
    )

    # Generated Assertions
    assert endpoint_1_POST_1_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "name") == flow_b_name
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(endpoint_1_POST_1_response, "id"), re.IGNORECASE)
    assert re.match(r"^\d{4}-\d{2}-\d{2}T", skyramp.get_response_value(endpoint_1_POST_1_response, "created"))

    # Request Body
    flow_a_id = skyramp.get_response_value(endpoint_1_POST_response, "id")
    flow_b_id = skyramp.get_response_value(endpoint_1_POST_1_response, "id")
    filter_POST_request_body = f'''{{
        "flows": {{
            "id": {{
                "any_": [
                    "{flow_a_id}",
                    "{flow_b_id}"
                ]
            }}
        }},
        "sort": "CREATED_ASC"
    }}'''

    # Execute Request
    filter_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/filter",
        method="POST",
        body=filter_POST_request_body
    )

    # Generated Assertions
    assert filter_POST_response.status_code == 200
    assert skyramp.get_response_value(filter_POST_response, "0.id") == flow_a_id
    assert skyramp.get_response_value(filter_POST_response, "0.name") == flow_a_name
    assert skyramp.get_response_value(filter_POST_response, "1.id") == flow_b_id
    assert skyramp.get_response_value(filter_POST_response, "1.name") == flow_b_name
    assert skyramp.get_response_value(filter_POST_response, "2.id") is None


if __name__ == "__main__":
    test_integration()
