# Generated by Skyramp v1.3.34 on 2026-07-21 01:01:24.040149468 +0000 UTC m=+343.101126779
# Command: skyramp generate contract rest http://localhost:4200/api/flows/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_flows_create_name_length_test.py \
# 		--output-dir /home/runner/work/prefect-sutboot/prefect-sutboot/tests/server/orchestration/api \
# 		--overwrite \
# 		--provider \
# 		--request-data {"name":"skyramp-name-length-1784595670"} \
# 		--response-status-code 201 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import re


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flows/ POST
def test_flows_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    flows_POST_request_body = r'''{
        "name": "skyramp-name-length-1784595670"
    }'''

    # Execute Request
    flows_POST_response = client.send_request(
        url=URL,
        path="/api/flows/",
        method="POST",
        body=flows_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert flows_POST_response.status_code == 201
    assert skyramp.get_response_value(flows_POST_response, "name") == "skyramp-name-length-1784595670"
    assert skyramp.get_response_value(flows_POST_response, "name_length") == len("skyramp-name-length-1784595670")
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(flows_POST_response, "id"), re.IGNORECASE)
    assert re.match(r"^\d{4}-\d{2}-\d{2}T", skyramp.get_response_value(flows_POST_response, "created"))
    assert re.match(r"^\d{4}-\d{2}-\d{2}T", skyramp.get_response_value(flows_POST_response, "updated"))


if __name__ == "__main__":
    test_flows_post()
