# Generated by Skyramp v1.3.34 on 2026-07-21 01:01:38.657524817 +0000 UTC m=+357.718502128
# Command: skyramp generate contract rest http://localhost:4200/api/flows/{id} \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_flows_read_name_length_test.py \
# 		--output-dir /home/runner/work/prefect-sutboot/prefect-sutboot/tests/server/orchestration/api \
# 		--overwrite \
# 		--parent-request-data id={"name": "skyramp-name-length-read-1784595670"} \
# 		--parent-status-code id=201 \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import re


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flows/{id} GET
def test_flows_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Provision parent flow
    flows_POST_request_body = r'''{
        "name": "skyramp-name-length-read-1784595670"
    }'''
    flows_POST_response = client.send_request(
        url=URL,
        path="/api/flows/",
        method="POST",
        body=flows_POST_request_body,
        headers=headers
    )
    assert flows_POST_response.status_code == 201
    id = skyramp.get_response_value(flows_POST_response, "id")

    # Execute Request
    flows_id_GET_response = client.send_request(
        url=URL,
        path="/api/flows/{id}",
        method="GET",
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert flows_id_GET_response.status_code == 200
    assert skyramp.get_response_value(flows_id_GET_response, "id") == id
    assert skyramp.get_response_value(flows_id_GET_response, "name") == "skyramp-name-length-read-1784595670"
    assert skyramp.get_response_value(flows_id_GET_response, "name_length") == len("skyramp-name-length-read-1784595670")
    assert re.match(r"^\d{4}-\d{2}-\d{2}T", skyramp.get_response_value(flows_id_GET_response, "created"))
    assert re.match(r"^\d{4}-\d{2}-\d{2}T", skyramp.get_response_value(flows_id_GET_response, "updated"))


if __name__ == "__main__":
    test_flows_id_get()
