# Generated by Skyramp v1.3.34 on 2026-07-21 01:01:44.219166386 +0000 UTC m=+363.280143708
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output integration_flows_filter_name_length_consistency_test.py \
# 		--output-dir /home/runner/work/prefect-sutboot/prefect-sutboot/tests/server/orchestration/api \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-sutboot/prefect-sutboot/tests/server/orchestration/api/scenario_flows_filter_name_length_consistency.json

# Import of required libraries
import skyramp
import os
import re
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "skyramp-name-length-filter-1784595670"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_1_POST_request_body
    )

    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "skyramp-name-length-filter-1784595670"
    assert skyramp.get_response_value(endpoint_1_POST_response, "name_length") == len("skyramp-name-length-filter-1784595670")
    created_flow_id = skyramp.get_response_value(endpoint_1_POST_response, "id")
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", created_flow_id, re.IGNORECASE)

    # Request Body
    filter_POST_request_body = r'''{
        "flows": {
            "name": {
                "any_": [
                    "skyramp-name-length-filter-1784595670"
                ]
            }
        }
    }'''

    # Execute Request
    filter_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/filter",
        method="POST",
        body=filter_POST_request_body
    )

    # Generated Assertions
    assert filter_POST_response.status_code == 200
    assert skyramp.get_response_value(filter_POST_response, "0.id") == created_flow_id
    assert skyramp.get_response_value(filter_POST_response, "0.name") == "skyramp-name-length-filter-1784595670"
    assert skyramp.get_response_value(filter_POST_response, "0.name_length") == len("skyramp-name-length-filter-1784595670")
    assert skyramp.get_response_value(filter_POST_response, "0.name_length") == skyramp.get_response_value(endpoint_1_POST_response, "name_length")
    assert skyramp.get_response_value(filter_POST_response, "1") is None


if __name__ == "__main__":
    test_integration()
